<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Arc.Ddsi.BgiDisassembler</RootNamespace>
    <AssemblyName>BgiDisassembler</AssemblyName>
    <Version>1.1.0</Version>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

</Project>
